package com.ars.data.repository

import android.content.Context
import android.net.Uri
import com.ars.core.model.Track
import com.ars.data.source.uri.ArtworkExtractor
import com.ars.data.source.uri.UriMetadataExtractor
import com.ars.domain.repository.TrackRepository
import com.ars.domain.usecase.import.ImportResult
import com.ars.domain.usecase.import.ImportUseCasePort
import dagger.hilt.android.qualifiers.ApplicationContext
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ImportRepositoryImpl @Inject constructor(
    @ApplicationContext private val context: Context,
    private val trackRepository: TrackRepository,
    private val metadataExtractor: UriMetadataExtractor,
    private val artworkExtractor: ArtworkExtractor
) : ImportUseCasePort {

    override suspend fun importFromUri(uri: Uri): ImportResult {
        // 1. Take persistent URI permission so we can play later without copying
        takePersistentPermission(uri)

        val uriString = uri.toString()

        // 2. Duplicate check by URI
        val existing = trackRepository.getTrackByUri(uriString)
        if (existing != null) {
            Timber.d("Duplicate detected: ${existing.title}")
            return ImportResult.Duplicate(existing)
        }

        // 3. Extract metadata
        val metadata = metadataExtractor.extract(uri)
            ?: return ImportResult.Error(IllegalArgumentException("Could not read audio metadata from $uri"))

        // 4. Insert track into DB (id=0 → auto-generated by Room)
        val draftTrack = Track(
            id = 0,
            uri = uriString,
            title = metadata.title,
            artist = metadata.artist,
            album = metadata.album,
            albumArtist = metadata.albumArtist,
            durationMs = metadata.durationMs,
            fileSizeBytes = metadata.fileSizeBytes,
            mimeType = metadata.mimeType,
            artworkUri = null,          // filled after we have the real ID
            trackNumber = metadata.trackNumber,
            year = metadata.year,
            bitrate = metadata.bitrate,
            sampleRate = metadata.sampleRate,
            isFavorite = false,
            dateAdded = System.currentTimeMillis(),
            lastPlayed = null,
            playCount = 0
        )
        val trackId = trackRepository.insertTrack(draftTrack)
        if (trackId <= 0L) {
            return ImportResult.Error(IllegalStateException("DB insert returned invalid id for $uriString"))
        }

        // 5. Extract artwork now that we have a stable trackId for the filename
        val artworkPath: String? = if (metadata.hasEmbeddedArt) {
            artworkExtractor.extractAndCache(uri, trackId)
        } else null

        // 6. Update track with artwork path
        val finalTrack = draftTrack.copy(id = trackId, artworkUri = artworkPath)
        trackRepository.updateTrack(finalTrack)

        Timber.i("Imported: ${finalTrack.title} (id=$trackId)")
        return ImportResult.Success(finalTrack)
    }

    private fun takePersistentPermission(uri: Uri) {
        try {
            context.contentResolver.takePersistableUriPermission(
                uri,
                android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION
            )
        } catch (e: SecurityException) {
            Timber.w("Could not persist URI permission for $uri: ${e.message}")
        }
    }
}
